doctrine_migrations:
  storage:
    table_storage:
      table_name: 'migration_versions'
      version_column_name: 'version'
      version_column_length: 50
      executed_at_column_name: 'executed_at'
  migrations_paths:
    'App\Migrations': '%kernel.project_dir%/migrations'
  all_or_nothing: true
