nelmio_security:
  clickjacking:
    paths:
      '^/.*': DENY

  external_redirects:
    abort: false
    log: true

  csp:
    hosts: []
    content_types: []
    enforce:
      level1_fallback: false
      browser_adaptive:
        enabled: false
      default-src:
        - 'none'
      connect-src:
        - 'self'
        - 'analytics.ahrefs.com'
      font-src:
        - 'self'
      frame-src:
        - '*.tradetracker.net'
      script-src:
        - 'self'
        - 'unsafe-eval'
        - 'unsafe-inline'
        - 'unpkg.com'
        - 'analytics.ahrefs.com'
        - 'cdn.ckeditor.com'
        - 'code.jquery.com'
        - '*.datatables.net'
        - '*.fontawesome.com'
      style-src:
        - 'self'
        - 'unsafe-inline'
        - 'code.jquery.com'
        - 'unpkg.com'
        - '*.datatables.net'
        - '*.tradetracker.net'
      img-src:
        - 'self'
        - 'data:'
        - 'unpkg.com'
        - 'api.mapbox.com'
        - 'code.jquery.com'
        - '*.buienradar.nl'
        - '*.datatables.net'
        - '*.tradetracker.net'
      block-all-mixed-content: true
      upgrade-insecure-requests: true

  content_type:
    nosniff: true

  referrer_policy:
    enabled: true
    policies:
      - 'no-referrer'
      - 'strict-origin-when-cross-origin'
